# --- User's custom definitions

# ---

MAXCOMPILER_QUOTE   := $(shell printf %q "$(MAXCOMPILERDIR)")

RUNRULE_ARGS        := 
RUNRULE_RUNENV      := LD_LIBRARY_PATH="$(MAXELEROSDIR)/lib:$(LD_LIBRARY_PATH)" 
RUNRULE_MAXFILES    := CNN_FW_Conv_V0.max  
RUNRULE_MAXFILES_H  := CNN_FW_Conv_V0.h 
RUNRULE_CFLAGS      := 
RUNRULE_LDFLAGS     := 

TARGET_EXEC         := CNN_FW_Conv_V0
TARGET_LIBRARY      := 


